# Generated by Django 6.0.3 on 2026-03-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_alter_user_options_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='chat_id'),
        ),
    ]
